### PR TITLE
Added basic contour functionality

### PR DESCRIPTION
**Pull request by mjziebarth**
Hi everyone,
started using gmt-python yesterday and really like the project. Since I'll be writing some solutions for my own use, I figured I may contribute them right away. So, I am leaning a bit on the pull-request-style of development and don't expect this to be ready to merge straight away.

## Changes proposed in this pull request
- Add function to call gmt contour from BasePlotting.

### Note
The code is copied from the plot function and is very basic so far. Tested only locally for crashes in Figure so far.

Looking forward to your input!

### CODE REVIEW

**Comment by leouieda** [comment]
@mjziebarth thank you submitting this! I really appreciate it :+1:

Don't worry too much about the whole flow of development, I'll try to help you through it. And there is no way to really break things. That's what all these automatic checks take care of.

I'm a little bit overwhelmed with the Scipy conference this week, so sorry for the late reply. I'll try to look over this on the weekend.

Thank you again for your contribution! It's really appreciated.

**Comment by leouieda** [comment]
@mjziebarth the code looks ok to me. Are you getting crashes?

**Comment by leouieda** [comment]
If not, then the only things we need are a bit more documentation and some tests. 

For the tests, please have a look at this: https://github.com/GenericMappingTools/gmt-python/blob/master/CONTRIBUTING.md#testing-plots Let me know if you need any help.

For the documentation, I'm thinking of adding a few examples to all modules. Would be willing to try to add an example plot using [our sphinx extension](https://www.gmtpython.xyz/latest/sphinxext.html)?

**Comment by mjziebarth** [comment]
Thanks for the feedback!

I added some test cases. Not the most sophisticated but should get the job done.
The tests ultimately fail on my local machine (TypeError with the gmt.Figure) but the images were generated. Let's see how this works with the CI.

I could add a test case for sphinx, but that should probably be a little bit more real-world, I guess?

**Comment by mjziebarth** [comment]
So right now there are errors left in some of the Travis runs. One is a one pixel width difference in the generated test images that prevents the comparison. From visual inspection, the images do not show obvious errors and it seems like the python 3.6 Travis runs without errors.

Another Travis run fails at some point before that.

Do you have any idea what could go wrong there or how that behavior could be fixed? I'm not familiar with the underlying testing framework.

Regarding the sphinx-example: Where would that go?

**Comment by leouieda** [comment]
@mjziebarth I'm going through the CI logs to try to see what went wrong. I found a problem with our CI builds on 3.5. It seems that our code formatter `black` only works on 3.6. I'll fix this first so that your tests can pass.

**Comment by akshmakov** [comment]
I had a need for contours as well, started working on this and then saw it was already done! Nice.

I can help rebase on top of the existing master branch so the PR can go through, but am waiting for this functionality!

+1

**Comment by akshmakov** [comment]
The branch rebases cleanly on master, meaning a merge back isn't required. For an up to date branch as an example https://github.com/nc5ng/gmt-python/tree/rebase/contour-pr-212

**Comment by mjziebarth** [comment]
Okay, I did it using this button of github. Not sure what that actually does but hope that's okay!

@leouieda Please excuse if you've been busy, but is there anything else I should do in this PR?

**Comment by leouieda** [comment]
@mjziebarth sorry for the absence. I was away on travel last week and spent this entire week trying to get things up and running again with the GMT conda package (so many headaches). We're up and running again now.

Only thing left to do here is list the `Figure.contour` method in `doc/api/index.rst`. After that, I'll merge as soon as the CIs builds are passing.

Thanks for your effort and your patience! I hope to see more of these :smiley:

**Comment by leouieda** [comment]
@akshmakov yeah, `grdcontour` is a different module with different inputs. Would you mind adding it in another PR?

**Comment by leouieda** [comment]
@mjziebarth there was a strange problem with your baseline images and I'm not entirely sure what caused it. I regenerated them on my machine and went ahead and added the API entry so we can merge this.

**Pull request merged**
