### PR TITLE
Support Python 3.7

### LINKED ISSUE #190: Add Python 3.7
This is a reminder to add Python 3.7 to testing which is planned to be [released on June 27, 2018](https://www.python.org/dev/peps/pep-0537/#id6). 

- [x] `.travis.yml`
- [x] `CLASSIFIERS` in `setup.py`

### PR DESCRIPTION
**Pull request by seisman**
Fixes #190.

## Changes proposed in this pull request

Add tests for Python 3.7 while keeping Python 3.6 as the default version.

### CODE REVIEW

**Comment by leouieda** [comment]
Thanks @seisman. It looks like it will still be a while before this will work. conda-forge has very few packages for 3.7 still and when we install `requirements.txt` python gets downgraded to 3.6.

**Comment by leouieda** [comment]
We can leave this open until there is more support from other packages. I don't think it will be long.

**Comment by seisman** [comment]
@leouieda I think this PR is ready to be merged.

**Comment by leouieda** [comment]
:+1:

**Pull request merged**
