### PR TITLE
wrapper for gmtlogo

### PR DESCRIPTION
**Pull request by seisman**
PR for issue #76.

### CODE REVIEW

**Comment by leouieda** [comment]
Thanks @seisman! This is perfect.

**Comment by seisman** [comment]
Travis fails for Python 3.5 after merging this PR into master.

**Comment by leouieda** [comment]
Yeah, I just noticed. It's failing all the image comparison tests. I'm trying to reproduce this on my machine to investigate what's going on. Let me know if you notice anything.

**Comment by leouieda** [comment]
@seisman found it. It's not your PR that broke things. It's the update of ghostscript to 9.22 that changed the images very slightly. I've been able to reproduce it on my machine and I'll make a patch with update baselines.

**Comment by leouieda** [comment]
#85 should fix this.

**Pull request merged**
